baseURL = "https://paralike.github.io/Paralike/"
#relativeURLs = true
languageCode = "en-us"
title = "My Digital Garden"
# theme = "hugo-digital-garden-theme"
copyright = "Adam Steiner"


[params]
  name = "Adam Steiner"
  description = "To create time so that everybody can do they find meaningful."
  initials = "AS"
  profile_picture = "/index/featured.jpg"
  googleAnalytics = ""

  [[params.social]]
    name = "Github"
    link = "https://github.com/Paralike"
    icon = "fab fa-github"

  [[params.social]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/adam-steiner-4453381a3/"
    icon = "fab fa-linkedin-in"


[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Digital Garden"
    url = "/garden/"
    weight = 3



[taxonomies]
  garden_tags = 'garden_tags'
  project_tags = 'project_tags'
  library_tags = 'library_tags'
  education_tags = 'education_tags'

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'